name: Lint

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint-commit-msg:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
      - name: Install deps
        run: npm install
      - name: Lint all commit messages in push
        run: |
          for sha in $(git rev-list ${{ github.event.before }}..${{ github.sha }}); do
            git show -s --format=%B $sha | npx commitlint
          done

  lint-code:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint
